######################################################################
# Automatically generated by qmake (2.01a) Mon May 28 15:47:40 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L/usr/local/lib -lwiringPi
