######################################################################
# Automatically generated by qmake (2.01a) Sun May 27 23:16:56 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L/usr/local/lib -lwiringPi
