######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 12 12:23:10 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L/usr/local/lib -l wiringPi

