######################################################################
# Automatically generated by qmake (2.01a) Sun Sep 29 20:22:45 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L/usr/local/lib -l wiringPi
