######################################################################
# Automatically generated by qmake (2.01a) Sat Jun 16 10:45:29 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L /usr/local/lib -l wiringPi
