######################################################################
# Automatically generated by qmake (2.01a) Fri May 25 09:29:03 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
LIBS += -L/usr/local/lib -lwiringPi
